# Generated by Django 5.2.5 on 2025-10-31 11:41

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('python_class', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('endpoint', models.CharField(default='', max_length=500)),
                ('key', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SmartAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=150)),
                ('duration', models.DurationField(default=datetime.timedelta)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive')], default='MODERATE', max_length=20)),
                ('investment', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('exchange', models.CharField(default='Unknown', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.advisor')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('explanation', models.CharField(max_length=500)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.advisor')),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.smartanalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volatile', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(max_length=500)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.advisor')),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.smartanalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.IntegerField()),
                ('avg_confidence', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tot_confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.smartanalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Suggest buy'), ('SELL', 'Suggest sell')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shares', models.IntegerField()),
                ('consensus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.consensus')),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.smartanalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
