# Generated by Django 5.2.5 on 2025-10-23 12:24

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('python_class', models.CharField(unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('endpoint', models.CharField(default='')),
                ('key', models.CharField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SmartAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField()),
                ('duration', models.DurationField(default=datetime.timedelta)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(unique=True)),
                ('company', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('BEAR', 'Market decline'), ('STAG', 'Mixed market'), ('BULL', 'Market optimism')], default='STAG', max_length=20)),
                ('risk', models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive')], default='MODERATE', max_length=20)),
                ('investment', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=10)),
                ('cash', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Suggest buy'), ('HOLD', 'Do not sell or buy'), ('SELL', 'Suggest sell'), ('STRONG_BUY', 'Definitely buy'), ('STRONG_SELL', 'Definitely sell')], default='HOLD', max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('explanation', models.CharField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advisor')),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.smartanalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('volatile', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.advisor')),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.smartanalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Consensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.IntegerField()),
                ('avg_confidence', models.DecimalField(decimal_places=2, max_digits=2)),
                ('tot_confidence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.smartanalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Suggest buy'), ('SELL', 'Suggest sell')], default='HOLD', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shares', models.IntegerField()),
                ('consensus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consensus')),
                ('sa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.smartanalysis')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
