# Generated by Django 5.2.5 on 2025-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='endpoint',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='python_class',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='consensus',
            name='avg_confidence',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='explanation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='explanation',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='smartanalysis',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(choices=[('BUY', 'Suggest buy'), ('SELL', 'Suggest sell')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
