# Generated by Django 5.2.5 on 2025-11-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stock_image_alter_stock_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='explanation',
            field=models.CharField(max_length=1000),
        ),
    ]
