# Generated by Django 5.2.5 on 2025-10-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_advisor_endpoint_alter_advisor_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='action',
        ),
    ]
