# Generated by Django 5.2.5 on 2025-11-10 13:11
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_discovery_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
