# Generated by Django 5.2.5 on 2025-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_discovery_created_recommendation_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='consensus',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
    ]
