# Generated by Django 5.2.5 on 2025-10-30 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stock_exchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='advisor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.advisor'),
        ),
        migrations.AlterField(
            model_name='consensus',
            name='sa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.smartanalysis'),
        ),
        migrations.AlterField(
            model_name='consensus',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.advisor'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='sa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.smartanalysis'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.advisor'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='sa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.smartanalysis'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='consensus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.consensus'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.smartanalysis'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
