# Generated by Django 5.2.5 on 2025-11-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_holding_consensus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='consensus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.consensus'),
        ),
    ]
