# Generated by Django 5.2.5 on 2025-11-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trade_consensus'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='explanation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='risk',
            field=models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive'), ('EXPERIMENTAL', 'Experimental')], default='MODERATE', max_length=20),
        ),
        migrations.CreateModel(
            name='SellInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(choices=[('STOP_LOSS', 'Stop Loss'), ('TARGET_PRICE', 'Target Price'), ('CS_FLOOR', 'CS Floor'), ('AFTER_DAYS', 'After Days')], max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discovery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.discovery')),
            ],
        ),
    ]
