# Generated by Django 5.2.5 on 2025-11-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trade_explanation_alter_profile_risk_sellinstruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='_price',
        ),
    ]
