# Generated by Django 5.2.5 on 2025-11-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_price_stock__price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
    ]
