# Generated by Django 5.2.5 on 2025-11-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_stock_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='_price',
            new_name='price',
        ),
    ]
