# Generated by Django 5.2.5 on 2025-11-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename__price_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='trend',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
