# Generated by Django 5.2.5 on 2025-11-27 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_stock_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellinstruction',
            name='instruction',
            field=models.CharField(choices=[('STOP_LOSS', 'Stop Loss'), ('TARGET_PRICE', 'Target Price'), ('CS_FLOOR', 'CS Floor'), ('AFTER_DAYS', 'After Days'), ('DESCENDING_TREND', 'Descending trend')], max_length=20),
        ),
    ]
