# Generated by Django 5.2.5 on 2025-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='score',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='discovery',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discovery',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
