# Generated by Django 5.2.5 on 2025-12-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_advisor_score_discovery_price_discovery_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='score',
            new_name='weight',
        ),
    ]
