# Generated by Django 5.2.5 on 2025-12-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_score_advisor_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='trend',
        ),
    ]
