# Generated by Django 5.2.5 on 2025-12-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_refactor_sell_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average cost basis at time of SELL (for P&L calculation)', max_digits=10, null=True),
        ),
    ]
