# Generated by Django 5.2.5 on 2025-12-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_trade_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('buy_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('gemini_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('gemini_comments', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_health', to='core.stock')),
            ],
            options={
                'verbose_name_plural': 'Health',
                'indexes': [models.Index(fields=['stock', '-updated'], name='core_health_stock_i_f7aa63_idx'), models.Index(fields=['-updated'], name='core_health_updated_46b0cf_idx')],
            },
        ),
    ]
