# Generated by Django 5.2.5 on 2025-12-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='core.stock'),
        ),
    ]
