# Generated by Django 5.2.5 on 2025-12-04 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_health_stock'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='health',
            name='core_health_stock_i_f7aa63_idx',
        ),
        migrations.RemoveIndex(
            model_name='health',
            name='core_health_updated_46b0cf_idx',
        ),
        migrations.RemoveField(
            model_name='health',
            name='buy_score',
        ),
        migrations.RemoveField(
            model_name='health',
            name='gemini_comments',
        ),
        migrations.RemoveField(
            model_name='health',
            name='gemini_score',
        ),
        migrations.RemoveField(
            model_name='health',
            name='updated',
        ),
        migrations.AddField(
            model_name='health',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health',
            name='score',
            field=models.DecimalField(decimal_places=1, default=50.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='health',
            index=models.Index(fields=['stock', '-created'], name='core_health_stock_i_e36bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='health',
            index=models.Index(fields=['-created'], name='core_health_created_753dfc_idx'),
        ),
    ]
