# Generated by Django 5.2.5 on 2025-12-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_health_core_health_stock_i_f7aa63_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='sa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.smartanalysis'),
            preserve_default=False,
        ),
    ]
