# Generated by Django 5.2.5 on 2025-12-07 19:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_health_sa'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='trade_cumulative',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='trade_daily',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
