# Generated by Django 5.2.5 on 2025-12-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_stock_sector_industry_website_beta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinstruction',
            name='instruction',
            field=models.CharField(choices=[('STOP_PRICE', 'Stop Loss (Price)'), ('TARGET_PRICE', 'Target Price (Price)'), ('STOP_PERCENTAGE', 'Stop Loss (Percentage)'), ('TARGET_PERCENTAGE', 'Target Price (Percentage)'), ('AFTER_DAYS', 'After Days'), ('DESCENDING_TREND', 'Descending trend'), ('END_WEEK', 'End of current week'), ('END_DAY', 'End of current day'), ('NOT_TRENDING', 'No longer trending (low volume)')], max_length=20),
        ),
    ]
