# Generated by Django 5.2.5 on 2025-12-12 13:21

from django.db import migrations, models


def backfill_holding_created(apps, schema_editor):
    """Backfill holding.created from first BUY trade for each holding."""
    Holding = apps.get_model('core', 'Holding')
    Trade = apps.get_model('core', 'Trade')
    
    # Get all holdings without a created timestamp
    holdings = Holding.objects.filter(created__isnull=True)
    
    updated_count = 0
    for holding in holdings:
        # Find the first BUY trade for this user/stock combination
        first_buy = Trade.objects.filter(
            user=holding.user,
            stock=holding.stock,
            action='BUY'
        ).order_by('created').first()
        
        if first_buy:
            holding.created = first_buy.created
            holding.save(update_fields=['created'])
            updated_count += 1
    
    print(f"Backfilled created timestamp for {updated_count} holdings from Trade records")


def reverse_backfill(apps, schema_editor):
    """Reverse migration - set created back to None."""
    Holding = apps.get_model('core', 'Holding')
    Holding.objects.all().update(created=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_sellinstruction_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, blank=True),
        ),
        migrations.RunPython(backfill_holding_created, reverse_backfill),
    ]
