# Generated by Django 5.2.5 on 2025-12-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_holding_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellinstruction',
            name='max_days',
            field=models.IntegerField(blank=True, help_text='Used for TARGET_DIMINISHING and STOP_AUGMENTING - number of days over which to adjust the price', null=True),
        ),
        migrations.AlterField(
            model_name='sellinstruction',
            name='instruction',
            field=models.CharField(choices=[('STOP_PRICE', 'Stop Loss (Price)'), ('TARGET_PRICE', 'Target Price (Price)'), ('STOP_PERCENTAGE', 'Stop Loss (Percentage)'), ('TARGET_PERCENTAGE', 'Target Price (Percentage)'), ('AFTER_DAYS', 'After Days'), ('DESCENDING_TREND', 'Descending trend'), ('END_WEEK', 'End of current week'), ('END_DAY', 'End of current day'), ('NOT_TRENDING', 'No longer trending (low volume)'), ('TARGET_DIMINISHING', 'Target Price (Diminishing)'), ('STOP_AUGMENTING', 'Stop Loss (Augmenting)')], max_length=20),
        ),
    ]
