# Generated by Django 5.2.5 on 2025-12-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_sellinstruction_max_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellinstruction',
            name='max_days',
        ),
    ]
