# Generated by Django 5.2.5 on 2025-12-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_sellinstruction_max_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinstruction',
            name='instruction',
            field=models.CharField(choices=[('STOP_PRICE', 'Stop Loss (Price)'), ('TARGET_PRICE', 'Target Price (Price)'), ('STOP_PERCENTAGE', 'Stop Loss (Percentage)'), ('TARGET_PERCENTAGE', 'Target Price (Percentage)'), ('AFTER_DAYS', 'After Days'), ('DESCENDING_TREND', 'Descending trend'), ('END_WEEK', 'End of current week'), ('END_DAY', 'End of current day'), ('NOT_TRENDING', 'No longer trending (low volume)'), ('TARGET_DIMINISHING', 'Target Price (Diminishing)'), ('STOP_AUGMENTING', 'Stop Loss (Augmenting)'), ('PERCENTAGE_DIMINISHING', 'Target Price (Percentage diminishing)'), ('PERCENTAGE_AUGMENTING', 'Stop Loss (Percentage augmenting)')], max_length=25),
        ),
    ]
