# Generated by Django 5.2.5

from django.db import migrations, models
from decimal import Decimal


def populate_value1_from_value(apps, schema_editor):
    SellInstruction = apps.get_model('core', 'SellInstruction')
    for instruction in SellInstruction.objects.all():
        if instruction.value is not None:
            instruction.value1 = instruction.value
            instruction.save()


def reverse_populate_value1_from_value(apps, schema_editor):
    SellInstruction = apps.get_model('core', 'SellInstruction')
    for instruction in SellInstruction.objects.all():
        if instruction.value1 is not None:
            instruction.value = instruction.value1
            instruction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_sellinstruction_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellinstruction',
            name='value1',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, help_text='Primary value (price, percentage, days, threshold, etc.)'),
        ),
        migrations.AddField(
            model_name='sellinstruction',
            name='value2',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True, help_text='Secondary value (e.g., max_days for diminishing/augmenting instructions)'),
        ),
        migrations.RunPython(populate_value1_from_value, reverse_populate_value1_from_value),
    ]

