# Generated by Django 5.2.5

from django.db import migrations
from decimal import Decimal


def populate_value2_for_diminishing_augmenting(apps, schema_editor):
    """
    Populate value2 (max_days) for existing diminishing and augmenting instructions.
    - TARGET_DIMINISHING, PERCENTAGE_DIMINISHING: value2 = 14 (default)
    - STOP_AUGMENTING, PERCENTAGE_AUGMENTING: value2 = 28 (default)
    """
    SellInstruction = apps.get_model('core', 'SellInstruction')
    
    # Update diminishing instructions (default: 14 days)
    diminishing_instructions = SellInstruction.objects.filter(
        instruction__in=['TARGET_DIMINISHING', 'PERCENTAGE_DIMINISHING'],
        value2__isnull=True
    )
    for instruction in diminishing_instructions:
        instruction.value2 = Decimal('14')
        instruction.save()
    
    # Update augmenting instructions (default: 28 days)
    augmenting_instructions = SellInstruction.objects.filter(
        instruction__in=['STOP_AUGMENTING', 'PERCENTAGE_AUGMENTING'],
        value2__isnull=True
    )
    for instruction in augmenting_instructions:
        instruction.value2 = Decimal('28')
        instruction.save()


def reverse_populate_value2_for_diminishing_augmenting(apps, schema_editor):
    """Reverse migration - set value2 back to None"""
    SellInstruction = apps.get_model('core', 'SellInstruction')
    
    SellInstruction.objects.filter(
        instruction__in=['TARGET_DIMINISHING', 'PERCENTAGE_DIMINISHING', 'STOP_AUGMENTING', 'PERCENTAGE_AUGMENTING']
    ).update(value2=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_value1_value2_to_sellinstruction'),
    ]

    operations = [
        migrations.RunPython(populate_value2_for_diminishing_augmenting, reverse_populate_value2_for_diminishing_augmenting),
    ]

