# Generated by Django 5.2.5 on 2026-01-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_populate_value2_for_diminishing_augmenting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Executed', 'Executed')], default='Pending', max_length=20)),
                ('explanation', models.CharField(max_length=500)),
                ('days', models.IntegerField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.advisor')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock')),
            ],
        ),
    ]
