# Generated by Django 5.2.5 on 2026-01-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_sellinstruction_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinstruction',
            name='instruction',
            field=models.CharField(choices=[('STOP_PRICE', 'Stop Loss (Price)'), ('TARGET_PRICE', 'Target Price (Price)'), ('STOP_PERCENTAGE', 'Stop Loss (Percentage)'), ('TARGET_PERCENTAGE', 'Target Price (Percentage)'), ('AFTER_DAYS', 'After Days'), ('DESCENDING_TREND', 'Descending trend'), ('END_WEEK', 'End of current week'), ('END_DAY', 'End of current day'), ('NOT_TRENDING', 'No longer trending (low volume)'), ('TARGET_DIMINISHING', 'Target Price (Diminishing)'), ('STOP_AUGMENTING', 'Stop Loss (Augmenting)'), ('PERCENTAGE_DIMINISHING', 'Target Price (Percentage diminishing)'), ('PERCENTAGE_AUGMENTING', 'Stop Loss (Percentage augmenting)'), ('PROFIT_TARGET', 'Target Profit (Fixed Dollar Amount'), ('PERCENTAGE_REBUY', 'Stop Loss with Rebuy on Drop'), ('PROFIT_FLAT', 'Price has flatlined')], max_length=25),
        ),
    ]
