# Generated by Django 5.2.5 on 2026-02-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_peaked_sell_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='meta',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
