# Generated by Django 5.2.5 on 2026-02-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_watchlist_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Executed', 'Executed'), ('Excluded', 'Excluded')], default='Pending', max_length=20),
        ),
    ]
