# Generated by Django 5.2.5 on 2026-03-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_watchlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='explanation',
            field=models.TextField(),
        ),
    ]
