# Generated by Django 5.2.5 on 2026-03-18 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_discovery_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.health'),
        ),
    ]
