# Generated by Django 5.2.5 on 2026-03-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_holding_volatile_consensus'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.profile'),
        ),
        migrations.AddField(
            model_name='trade',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.profile'),
        ),
    ]
