# Generated by Django 5.2.5 on 2026-03-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_holding_fund_trade_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.profile'),
        ),
    ]
