# Generated by Django 5.2.5 on 2026-03-25

from django.db import migrations, models
from django.db.models import F


def backfill_profile_created(apps, schema_editor) -> None:
    """
    Backfill Profile.created from the legacy 1:1 assumption (user.date_joined).

    Only fills rows where created is NULL so we don't override admin/user-set values.
    """
    Profile = apps.get_model("core", "Profile")
    Profile.objects.filter(created__isnull=True).update(created=F("user__date_joined"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_snapshot_fund"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, blank=True
            ),
        ),
        migrations.RunPython(backfill_profile_created, migrations.RunPython.noop),
    ]

