# Generated by Django 5.2.5 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_snapshot_fund"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, blank=True
            ),
        ),
    ]

