# Generated by Django 5.2.5 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_profile_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="spread",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                choices=[
                    ("MEGA", "MEGA"),
                    ("LARGE", "LARGE"),
                    ("MEDIUM", "MEDIUM"),
                    ("SMALL", "SMALL"),
                    ("MICRO", "MICRO"),
                ],
            ),
        ),
    ]

