# Generated by Django 5.2.5 on 2026-03-25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_profile_spread"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avg_spend",
        ),
    ]

