# Generated by Django 5.2.5 on 2026-03-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_profile_avg_spend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='min_score',
        ),
        migrations.AlterField(
            model_name='profile',
            name='risk',
            field=models.CharField(choices=[('CONSERVATIVE', 'Conservative'), ('MODERATE', 'Moderate'), ('AGGRESSIVE', 'Aggressive'), ('RECKLESS', 'Reckless')], default='MODERATE', max_length=20),
        ),
    ]
