# Generated by Django 5.2.5 on 2026-04-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_profile_min_score_alter_profile_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sentiment',
            field=models.CharField(choices=[('STRONG_BULL', 'STRONG_BULL'), ('BULL', 'BULL'), ('STAG', 'STAG'), ('AUTO', 'AUTO'), ('BEAR', 'BEAR'), ('STRONG_BEAR', 'STRONG_BEAR')], default='AUTO', max_length=16),
        ),
        migrations.AlterField(
            model_name='profile',
            name='risk',
            field=models.CharField(choices=[('CONSERVATIVE', 'CONSERVATIVE'), ('MODERATE', 'MODERATE'), ('AGGRESSIVE', 'AGGRESSIVE'), ('RECKLESS', 'RECKLESS')], default='MODERATE', max_length=20),
        ),
    ]
