# Generated by Django 5.2.5 on 2026-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_snapshot_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='blob',
            field=models.TextField(blank=True, default=''),
        ),
    ]
