# Generated by Django 5.2.5 on 2026-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_advisor_blob'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
