# Generated by Django 5.2.5

from django.db import migrations


def migrate_target_percentage_to_target_price(apps, schema_editor):
    """
    Existing TARGET_PERCENTAGE rows store a dollar target (discovery price × multiplier).
    Re-label them as TARGET_PRICE; new discoveries store a multiplier on TARGET_PERCENTAGE.
    """
    SellInstruction = apps.get_model('core', 'SellInstruction')
    updated = SellInstruction.objects.filter(instruction='TARGET_PERCENTAGE').update(
        instruction='TARGET_PRICE'
    )
    if updated:
        print(f"Migrated {updated} TARGET_PERCENTAGE -> TARGET_PRICE (value1 unchanged)")


def reverse_migrate(apps, schema_editor):
    # Not reversible: new TARGET_PRICE rows may be created after this migration.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_push_device'),
    ]

    operations = [
        migrations.RunPython(
            migrate_target_percentage_to_target_price,
            reverse_migrate,
        ),
    ]
