# Generated by Django 5.2.5 on 2026-05-20 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_flux_advisor_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('financial', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('valuation', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('intrinsic', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('consensus', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('sector', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', '-created'], name='core_assess_stock_i_9bab00_idx')],
            },
        ),
    ]
