# Generated by Django 5.2.5 on 2026-05-20 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assessment'),
        ),
    ]
