# Generated by Django 5.2.5 on 2026-05-20 10:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_discovery_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weighted v2 composite (0–100) from component scores.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), help_text='Discovery trigger multiplier (e.g. Edgar 1.2); not component model weights.', max_digits=5),
        ),
    ]
