# Generated by Django 5.2.5 on 2026-05-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_assessment_score_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='weight',
        ),
    ]
