# Generated by Django 5.2.5 on 2026-06-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_advisor_pulse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='opp_price_blend',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Price score used in opportunity blend (after distress cap).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='opp_valuation_blend',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Valuation score used in opportunity blend (after distress cap).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sellinstruction',
            name='instruction',
            field=models.CharField(choices=[('STOP_PRICE', 'Stop Loss (Price)'), ('TARGET_PRICE', 'Target Price (Price)'), ('STOP_PERCENTAGE', 'Stop Loss (Percentage)'), ('TARGET_PERCENTAGE', 'Target Price (Percentage)'), ('TARGET_INTRADAY', 'Target Intraday'), ('AFTER_DAYS', 'After Days'), ('DESCENDING_TREND', 'Descending trend'), ('END_WEEK', 'End of current week'), ('END_DAY', 'End of current day'), ('NOT_TRENDING', 'No longer trending (low volume)'), ('TARGET_DIMINISHING', 'Target Price (Diminishing)'), ('STOP_AUGMENTING', 'Stop Loss (Augmenting)'), ('PERCENTAGE_DIMINISHING', 'Target Price (Percentage diminishing)'), ('PERCENTAGE_AUGMENTING', 'Stop Loss (Percentage augmenting)'), ('PROFIT_TARGET', 'Target Profit (Fixed Dollar Amount'), ('PERCENTAGE_REBUY', 'Loss - will gamble a Rebuy'), ('PROFIT_FLAT', 'Price flatlined'), ('PEAKED', 'Sell when down X% from peak since purchase')], max_length=25),
        ),
        migrations.AlterField(
            model_name='sellinstruction',
            name='value1',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Primary value (price, percentage, days, threshold, etc.)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='sellinstruction',
            name='value2',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Secondary value (e.g., max_days for diminishing/augmenting instructions)', max_digits=14, null=True),
        ),
    ]
